equisoft-actions/semgrep:
  - source: bin/semgrep.sh
    dest: files/semgrep.bash

equisoft-actions/docker-sast:
  - source: bin/docker-sast.sh
    dest: files/docker-sast.sh

equisoft-actions/docker-sbom:
  - source: bin/docker-sbom.sh
    dest: files/docker-sbom.sh

equisoft-actions/scan-secrets:
  - source: bin/gitleaks.bash
    dest: files/gitleaks.bash
  - source: gitleaks.toml
    dest: files/gitleaks.toml
