module.export = {
  rules: {
    "brace-style": ["error","stroustrup",{"allowSingleLine": true}],
    "camelcase": "off",
    "class-methods-use-this": "off",
    "comma-dangle": "off",
    "func-names": "off",
    "import/extensions": "off",
    "import/no-extraneous-dependencies": "off",
    "indent": ["error", "tab", { "SwitchCase": 1 }],
    "jsx-a11y/label-has-for": "off",
    "keyword-spacing": "off",
    "max-len": [2, 220, 2, {"ignoreUrls": true,"ignoreComments": false}],
    "new-cap": "off",
    "no-tabs": "off",
    "no-case-declarations": "off",
    "no-console": "off",
    "no-mixed-operators": ["error", { "allowSamePrecedence": true }],
    "no-param-reassign": "warn",
    "no-plusplus": ["error", { "allowForLoopAfterthoughts": true }],
    "no-cond-assign": ["error", "except-parens"],
    "no-return-assign": ["error", "except-parens"],
    "no-undef": "warn",
    "no-underscore-dangle": "off",
    "object-curly-newline": ["error",{"multiline": true}],
    "object-shorthand": "warn",
    "prefer-arrow-callback": "off",
    "prefer-template": "off",
    "quotes": ["warn","single"],
    "react/jsx-filename-extension": "off",
    "react/jsx-indent": "off",
    "react/jsx-indent-props": ["error", "tab"],
    "react/jsx-no-bind": "warn",
    "react/jsx-no-undef": "warn",
    "react/prefer-es6-class": "off",
    "react/prop-types": "off",
    "react/require-extension": "off",
    "react/sort-comp": "off",
    "space-before-function-paren": "off",
    "vars-on-top": "off"
  }
}
