on:
  push:
    branches:
      - master
      - test

name: release-please

jobs:
  release-please:
    environment: release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          target-branch: test
          token: ${{ secrets.ADMIN_PAT }}
