on:
  push:
    branches:
      - master
      - dev/QCTECH-1055-3

name: release-please

jobs:
  release-please:
    environment: release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          target-branch: dev/QCTECH-1055-3
          token: ${{ secrets.ADMIN_PAT }}
