name: Sync External Resources

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: repo-sync
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: "Sync files to equisoft-actions/*"
        uses: BetaHuhn/repo-file-sync-action@v1.21.1
        with:
          TEAM_REVIEWERS: equisoft-actions/harmony
          CONFIG_PATH: .github/sync/equisoft-actions.yml
          COMMIT_EACH_FILE: false
          COMMIT_PREFIX: 🎶
          GH_PAT: ${{ secrets.EQUISOFT_ACTIONS_PAT }}
          OVERWRITE_EXISTING_PR: true
          PR_LABELS: standards

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: sync
    if: always()
    steps:
      - name: Post workflow status
        uses: equisoft-actions/notify-workflow-status@v2
        with:
          needs: ${{ toJSON(needs) }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: ${{ github.event.repository.custom_properties.ci_slack_channel }}
