name: Sync External Resources

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: repo-sync
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: "Sync files to kronostechnologies/*"
        uses: BetaHuhn/repo-file-sync-action@v1.17.0
        with:
          TEAM_REVIEWERS: kronostechnologies/harmonie
          CONFIG_PATH: .github/sync/kronostechnologies.yml
          COMMIT_EACH_FILE: false
          COMMIT_PREFIX: 🎶
          GH_PAT: ${{ secrets.GHCR_TOKEN }}
          OVERWRITE_EXISTING_PR: true
          PR_LABELS: standards

      - name: "Sync files to equisoft-actions/*"
        uses: BetaHuhn/repo-file-sync-action@v1.17.0
        with:
          TEAM_REVIEWERS: equisoft-actions/harmonie
          CONFIG_PATH: .github/sync/equisoft-actions.yml
          COMMIT_EACH_FILE: false
          COMMIT_PREFIX: 🎶
          GH_PAT: ${{ secrets.EQUISOFT_ACTIONS_PAT }}
          OVERWRITE_EXISTING_PR: true
          PR_LABELS: standards

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: sync
    steps:
      - name: Post workflow status
        uses: kronostechnologies/actions/notify-workflow-status@v0.0.22
        with:
          needs: ${{ toJSON(needs) }}
          slack-webhook-url: ${{ secrets.OPS_CI_WEBHOOK_URL }}
