name: Validate actions workflows

on:
  merge_group:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate-github-workflows:
    name: Check workflow files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: equisoft-actions/with-asdf-vm@v2
      - name: Check workflow files
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          make check.workflows
