on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate-renovate:
    runs-on: ubuntu-latest
    env:
      FILES: renovate-config.json renovate-base.json
      SCHEMA_URL: https://docs.renovatebot.com/renovate-schema.json
    steps:
      - uses: actions/checkout@v3
      - uses: equisoft-actions/with-asdf-vm@v1
      - run: make check.renovate
